/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Core.Arbol.AVL;
import Core.Arbol.OperacionesArbol;
import Core.CursoManager;
import Core.controllers.Controladores;
import Core.controllers.utils.Response;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Esteban
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    AVL tree;
    CursoManager CM;
    Scanner sc;
    Controladores controlador;
    public interfaz() {
        initComponents();
        this.tree = AVL.getInstance();
        this.CM = CursoManager.getInstance();
        this.controlador = new Controladores(CM, tree);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SideButtons = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EliminarIDTF = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        EliminarMetricaBT = new javax.swing.JButton();
        EliminarMetricaTF = new javax.swing.JTextField();
        InsertarPanel = new javax.swing.JPanel();
        InsertarTF = new javax.swing.JTextField();
        InsertarBoton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        masPosButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        instanteTF = new javax.swing.JTextField();
        creacionFechaButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        minTF = new javax.swing.JTextField();
        maxTF = new javax.swing.JTextField();
        ranClasesButton = new javax.swing.JButton();
        masReseñasBox = new javax.swing.JComboBox<>();
        masPromedioButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InsertarLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BuscarID = new javax.swing.JButton();
        BuscarMetrica = new javax.swing.JButton();
        BuscarIDTF = new javax.swing.JTextField();
        BuscarMetricaTF = new javax.swing.JTextField();
        RecorridoNiveles = new javax.swing.JButton();
        MainTree = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        TreeSite = new javax.swing.JScrollPane();
        bigtree = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        InfoTF = new javax.swing.JTextField();
        InfoCompleta = new javax.swing.JButton();
        Nivel = new javax.swing.JButton();
        FBalanceo = new javax.swing.JButton();
        Padre = new javax.swing.JButton();
        Abuelo = new javax.swing.JButton();
        Tio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        MetricaTF = new javax.swing.JTextField();
        InfoCoMetrica = new javax.swing.JButton();
        NivelMetrica = new javax.swing.JButton();
        PadreM = new javax.swing.JButton();
        AbueloM = new javax.swing.JButton();
        FBalanceoMetrica = new javax.swing.JButton();
        TioM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SideButtons.setBackground(new java.awt.Color(0, 0, 153));
        SideButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EliminarIDTF.setText("ID");

        deleteButton.setText("Aceptar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Eliminar");

        EliminarMetricaBT.setText("Aceptar");
        EliminarMetricaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMetricaBTActionPerformed(evt);
            }
        });

        EliminarMetricaTF.setText("Por metrica");
        EliminarMetricaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMetricaTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarIDTF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EliminarMetricaBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EliminarMetricaTF)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(EliminarIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarMetricaBT)
                    .addComponent(EliminarMetricaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        InsertarPanel.setBackground(new java.awt.Color(102, 102, 255));
        InsertarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        InsertarTF.setColumns(5);
        InsertarTF.setText("ID");
        InsertarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarTFActionPerformed(evt);
            }
        });

        InsertarBoton.setText("Aceptar");
        InsertarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertarPanelLayout = new javax.swing.GroupLayout(InsertarPanel);
        InsertarPanel.setLayout(InsertarPanelLayout);
        InsertarPanelLayout.setHorizontalGroup(
            InsertarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertarTF, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        InsertarPanelLayout.setVerticalGroup(
            InsertarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertarPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(InsertarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarBoton)
                    .addComponent(InsertarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        masPosButton.setText("Buscar");
        masPosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masPosButtonMouseClicked(evt);
            }
        });
        masPosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPosButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Filtros");

        instanteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instanteTFActionPerformed(evt);
            }
        });

        creacionFechaButton.setText("Buscar");
        creacionFechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creacionFechaButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Por rango de clases");

        minTF.setText("Min");

        maxTF.setText("Max");

        ranClasesButton.setText("Buscar");
        ranClasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranClasesButtonActionPerformed(evt);
            }
        });

        masReseñasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mas positivas que el promedio", "Mas negativas que el promedio", "Mas neutras que el promedio" }));

        masPromedioButton.setText("Buscar");
        masPromedioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masPromedioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar por fecha en ISO-8601");

        jLabel5.setText("Buscar por tipo de reseña superior al promedio");

        jLabel6.setText("Buscar los que tienen mas reseñas positivas que negativas y neutras");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masPosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(creacionFechaButton)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(masReseñasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(masPromedioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(instanteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(minTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(102, 102, 102)
                            .addComponent(maxTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(ranClasesButton)))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(masPosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masReseñasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masPromedioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instanteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creacionFechaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ranClasesButton)
                    .addComponent(maxTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        InsertarLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InsertarLabel.setText("Insertar");

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        jLabel7.setText("Buscar");

        BuscarID.setText("Aceptar");
        BuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIDActionPerformed(evt);
            }
        });

        BuscarMetrica.setText("Aceptar");
        BuscarMetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMetricaActionPerformed(evt);
            }
        });

        BuscarIDTF.setText("ID");
        BuscarIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarIDTFActionPerformed(evt);
            }
        });

        BuscarMetricaTF.setText("Por metrica");
        BuscarMetricaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMetricaTFActionPerformed(evt);
            }
        });

        RecorridoNiveles.setText("Recorrido por niveles");
        RecorridoNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecorridoNivelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(BuscarID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(BuscarMetrica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BuscarMetricaTF))
                    .addComponent(RecorridoNiveles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarID)
                    .addComponent(BuscarIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarMetrica)
                    .addComponent(BuscarMetricaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RecorridoNiveles)
                .addContainerGap())
        );

        javax.swing.GroupLayout SideButtonsLayout = new javax.swing.GroupLayout(SideButtons);
        SideButtons.setLayout(SideButtonsLayout);
        SideButtonsLayout.setHorizontalGroup(
            SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideButtonsLayout.createSequentialGroup()
                .addGroup(SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SideButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SideButtonsLayout.createSequentialGroup()
                                .addComponent(InsertarLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SideButtonsLayout.createSequentialGroup()
                    .addComponent(InsertarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        SideButtonsLayout.setVerticalGroup(
            SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertarLabel)
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(SideButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SideButtonsLayout.createSequentialGroup()
                    .addComponent(InsertarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 770, Short.MAX_VALUE)))
        );

        jPanel1.add(SideButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 840));

        MainTree.setBackground(new java.awt.Color(0, 0, 204));
        MainTree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TitlePanel.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resultados");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane2.setViewportView(resultArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(189, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("resultados ", jPanel4);

        bigtree.setBackground(new java.awt.Color(102, 102, 255));
        bigtree.setText("Arbol");
        TreeSite.setViewportView(bigtree);

        jTabbedPane2.addTab("Arbol", TreeSite);

        jLabel9.setText("Buscar informacion del nodo ");

        InfoTF.setText("ID");
        InfoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoTFActionPerformed(evt);
            }
        });

        InfoCompleta.setText("Info Completa");
        InfoCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCompletaActionPerformed(evt);
            }
        });

        Nivel.setText("Nivel");
        Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelActionPerformed(evt);
            }
        });

        FBalanceo.setText("Factor de Balanceo");
        FBalanceo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBalanceoActionPerformed(evt);
            }
        });

        Padre.setText("Padre");
        Padre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PadreActionPerformed(evt);
            }
        });

        Abuelo.setText("Abuelo");
        Abuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbueloActionPerformed(evt);
            }
        });

        Tio.setText("Tio");
        Tio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TioActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar informacion del nodo ");

        MetricaTF.setText("Metrica");

        InfoCoMetrica.setText("Info Completa");
        InfoCoMetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCoMetricaActionPerformed(evt);
            }
        });

        NivelMetrica.setText("Nivel");
        NivelMetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivelMetricaActionPerformed(evt);
            }
        });

        PadreM.setText("Padre");
        PadreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PadreMActionPerformed(evt);
            }
        });

        AbueloM.setText("Abuelo");
        AbueloM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbueloMActionPerformed(evt);
            }
        });

        FBalanceoMetrica.setText("Factor de Balanceo");
        FBalanceoMetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FBalanceoMetricaActionPerformed(evt);
            }
        });

        TioM.setText("Tio");
        TioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TioMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InfoCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(Padre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Abuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FBalanceo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(496, 496, 496))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MetricaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InfoCoMetrica, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(PadreM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AbueloM, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(NivelMetrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TioM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FBalanceoMetrica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(496, 496, 496))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(InfoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoCompleta)
                    .addComponent(FBalanceo)
                    .addComponent(Nivel))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Padre)
                    .addComponent(Abuelo)
                    .addComponent(Tio))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(MetricaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoCoMetrica)
                    .addComponent(NivelMetrica)
                    .addComponent(FBalanceoMetrica))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TioM)
                    .addComponent(AbueloM)
                    .addComponent(PadreM))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Informacion del nodo", jPanel6);

        javax.swing.GroupLayout MainTreeLayout = new javax.swing.GroupLayout(MainTree);
        MainTree.setLayout(MainTreeLayout);
        MainTreeLayout.setHorizontalGroup(
            MainTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainTreeLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        MainTreeLayout.setVerticalGroup(
            MainTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainTreeLayout.createSequentialGroup()
                .addComponent(TitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jPanel1.add(MainTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 940, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarBotonActionPerformed
        String idTexto = InsertarTF.getText();
        InsertarTF.setText("");
        Response response = controlador.insertarNodo(idTexto);
        if(response.isSuccess()){
        try {
            BufferedImage img = ImageIO.read(new File("arbol.png"));
            bigtree.setIcon(new ImageIcon(img));

            bigtree.revalidate();
            bigtree.repaint();

        } catch (IOException e) {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
        
    }//GEN-LAST:event_InsertarBotonActionPerformed

    private void InsertarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarTFActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_InsertarTFActionPerformed

    private void masPosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masPosButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masPosButtonMouseClicked

    private void creacionFechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creacionFechaButtonActionPerformed
        //reinicia textarea
        //listo
        resultArea.setText(""); 
        
        String creacionStr = instanteTF.getText();
        Response res = controlador.isAfter(creacionStr);
        
        if(res.isSuccess()){

            //obtencion de ids
                Instant creacion = null;
                creacion = Instant.parse(creacionStr);
                ArrayList<String> creadosDespues= new ArrayList<>();
                creadosDespues = OperacionesArbol.getAfterDate(tree.getRaiz(), creacion);

                //se ponen en el textarea
                if(creadosDespues.isEmpty()){
                 resultArea.append("No se encontraron nodos");
                } else{
                    for(String id :creadosDespues){
                        
                    resultArea.append(id + "\n");
                   }
                }

                javax.swing.JOptionPane.showMessageDialog(this, "exito");

        }else{
                javax.swing.JOptionPane.showMessageDialog(this, "fecha invalida");
        }
        
    }//GEN-LAST:event_creacionFechaButtonActionPerformed

    private void masPosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPosButtonActionPerformed
    //listo        
    //reinicia textarea
        resultArea.setText(""); 
        ArrayList<String> masRevs = new ArrayList<>();
        //lista de ids de los nodos que cumplen eso
         masRevs = OperacionesArbol.highlyGraded(tree.getRaiz());
         if(masRevs.isEmpty()){
             resultArea.append("No se encontraron nodos");
         } else{
             for(String id : masRevs){
             resultArea.append(id + "\n");
            }
         }
         
    }//GEN-LAST:event_masPosButtonActionPerformed

    private void ranClasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranClasesButtonActionPerformed
         //listo
        //reinicia textarea
        resultArea.setText(""); 
        
        
        ArrayList<String> clasesEnRango = new ArrayList<>();
        Response response = controlador.clasesEnRango(minTF.getText(),maxTF.getText());
        
        //si es exito:
        if (response.isSuccess()){
            try{
                int minVal = Integer.parseInt(minTF.getText());
                int maxVal = Integer.parseInt(maxTF.getText());
                clasesEnRango = OperacionesArbol.classesInRange(tree.getRaiz(), minVal, maxVal);

                if(clasesEnRango.isEmpty()){
                     resultArea.append("No se encontraron nodos");
                 } else{
                     for(String id : clasesEnRango){
                     resultArea.append(id + "\n");
                    }
                 }
            } catch(NumberFormatException e){
            }
             javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }else{
             javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
        
    }//GEN-LAST:event_ranClasesButtonActionPerformed

    private void masPromedioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masPromedioButtonActionPerformed
        resultArea.setText(""); 
        ArrayList<String> masPromedio= new ArrayList<>();
        
        String opcion = masReseñasBox.getSelectedItem().toString();
        //"Mas positivas que el promedio", "Mas negativas que el promedio", "Mas neutras que el promedio"
        //se llena la lista, p
        if(opcion.equalsIgnoreCase("Mas positivas que el promedio")){
            masPromedio = OperacionesArbol.posHigherThanAvg(tree.getRaiz(), tree);
        }else if(opcion.equalsIgnoreCase("Mas negativas que el promedio")){
            masPromedio = OperacionesArbol.negHigherThanAvg(tree.getRaiz(), tree);
        }else if(opcion.equalsIgnoreCase("Mas neutras que el promedio")){
            masPromedio = OperacionesArbol.neutHigherThanAvg(tree.getRaiz(), tree);
        }
        
        
        //se llena el textArea
        if(masPromedio.isEmpty()){
             resultArea.append("No se encontraron nodos");
         } else{
             for(String id : masPromedio){
             resultArea.append(id + "\n");
            }
         }
        
        
    }//GEN-LAST:event_masPromedioButtonActionPerformed

    private void instanteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instanteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instanteTFActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String idTexto = EliminarIDTF.getText();
        Response response = controlador.borrarNodo(idTexto);
        if(response.isSuccess()){
        try {
            BufferedImage img = ImageIO.read(new File("arbol.png"));
            bigtree.setIcon(new ImageIcon(img));

            bigtree.revalidate();
            bigtree.repaint();

        } catch (IOException e) {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void EliminarMetricaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMetricaBTActionPerformed
        String metrica = EliminarMetricaTF.getText();
        Response response = controlador.borrarNodoMetrica(metrica);
        if(response.isSuccess()){
        try {
            BufferedImage img = ImageIO.read(new File("arbol.png"));
            bigtree.setIcon(new ImageIcon(img));

            bigtree.revalidate();
            bigtree.repaint();

        } catch (IOException e) {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_EliminarMetricaBTActionPerformed

    private void EliminarMetricaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMetricaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMetricaTFActionPerformed

    private void RecorridoNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecorridoNivelesActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, this.tree.porNiveles(this.tree.getRaiz()));
    }//GEN-LAST:event_RecorridoNivelesActionPerformed

    private void BuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIDActionPerformed
        String idTexto = BuscarIDTF.getText();
        Response response = controlador.BuscarID(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_BuscarIDActionPerformed

    private void InfoCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCompletaActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.InfoCompleta(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_InfoCompletaActionPerformed

    private void InfoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoTFActionPerformed

    private void NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.NivelNodo(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_NivelActionPerformed

    private void FBalanceoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBalanceoActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.FactBalance(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_FBalanceoActionPerformed

    private void PadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PadreActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.Padre(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene padre");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_PadreActionPerformed

    private void AbueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbueloActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.Abuelo(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene abuelo");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_AbueloActionPerformed

    private void TioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TioActionPerformed
        String idTexto = InfoTF.getText();
        Response response = controlador.Tio(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene tio");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_TioActionPerformed

    private void AbueloMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbueloMActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.AbueloMetrica(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene abuelo");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_AbueloMActionPerformed

    private void InfoCoMetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCoMetricaActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.InfoCompletaMetrica(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_InfoCoMetricaActionPerformed

    private void NivelMetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivelMetricaActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.NivelMetrica(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_NivelMetricaActionPerformed

    private void FBalanceoMetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FBalanceoMetricaActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.FBalanceoMetrica(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_FBalanceoMetricaActionPerformed

    private void PadreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PadreMActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.PadreMetrica(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene padre");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_PadreMActionPerformed

    private void TioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TioMActionPerformed
        String idTexto = MetricaTF.getText();
        Response response = controlador.TioMetrica(idTexto);
        if(response.isSuccess()){
            if(response.getObject()!= null){
                javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Este nodo no tiene tio");
            }
        
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_TioMActionPerformed

    private void BuscarIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarIDTFActionPerformed

    private void BuscarMetricaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMetricaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarMetricaTFActionPerformed

    private void BuscarMetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMetricaActionPerformed
        String idTexto = BuscarMetricaTF.getText();
        Response response = controlador.BuscarMetrica(idTexto);
        if(response.isSuccess()){
        javax.swing.JOptionPane.showMessageDialog(this, (String) response.getObject());
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, response.getMessage());
        }
    }//GEN-LAST:event_BuscarMetricaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abuelo;
    private javax.swing.JButton AbueloM;
    private javax.swing.JButton BuscarID;
    private javax.swing.JTextField BuscarIDTF;
    private javax.swing.JButton BuscarMetrica;
    private javax.swing.JTextField BuscarMetricaTF;
    private javax.swing.JTextField EliminarIDTF;
    private javax.swing.JButton EliminarMetricaBT;
    private javax.swing.JTextField EliminarMetricaTF;
    private javax.swing.JButton FBalanceo;
    private javax.swing.JButton FBalanceoMetrica;
    private javax.swing.JButton InfoCoMetrica;
    private javax.swing.JButton InfoCompleta;
    private javax.swing.JTextField InfoTF;
    private javax.swing.JButton InsertarBoton;
    private javax.swing.JLabel InsertarLabel;
    private javax.swing.JPanel InsertarPanel;
    private javax.swing.JTextField InsertarTF;
    private javax.swing.JPanel MainTree;
    private javax.swing.JTextField MetricaTF;
    private javax.swing.JButton Nivel;
    private javax.swing.JButton NivelMetrica;
    private javax.swing.JButton Padre;
    private javax.swing.JButton PadreM;
    private javax.swing.JButton RecorridoNiveles;
    private javax.swing.JPanel SideButtons;
    private javax.swing.JButton Tio;
    private javax.swing.JButton TioM;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JScrollPane TreeSite;
    private javax.swing.JLabel bigtree;
    private javax.swing.JButton creacionFechaButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField instanteTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton masPosButton;
    private javax.swing.JButton masPromedioButton;
    private javax.swing.JComboBox<String> masReseñasBox;
    private javax.swing.JTextField maxTF;
    private javax.swing.JTextField minTF;
    private javax.swing.JButton ranClasesButton;
    private javax.swing.JTextArea resultArea;
    // End of variables declaration//GEN-END:variables
}
